trigger:
- master
- feature/*

jobs:
- job: rustfmt
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      rustup component add rustfmt
    displayName: Install rustfmt

  - script: |
      cd padre
      cargo fmt --all -- --check
    displayName: Check formatting

- job: padre_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      cd padre
      cargo test -- --nocapture
    env:
      RUST_BACKTRACE: 1
    displayName: Run Padre CLI unit testing

  - script: |
      sudo apt-get install software-properties-common python3 python3-pip
      pip3 install behave
    displayName: Install python dependencies

  - script: |
      cd padre/integration
      behave
    displayName: Run Padre CLI integration testing

- job: vim_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      sudo add-apt-repository -y ppa:jonathonf/vim
      sudo apt-get update
      sudo apt-get install -y vim
    displayName: Install VIM and plugins

  - script: |
      sudo apt-get install -y lldb
    displayName: Install lldb

  - script: |
      cd padre
      cargo build
