trigger:
- master
- feature/*

jobs:
- job: A
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust

  - script: |
        rustc -Vv
        cargo -V
    displayName: Query rust and cargo versions

  - script: |
      rustup component add rustfmt
    displayName: Install rustfmt

  - script: |
      cd rust
      cargo fmt --all -- --check
    displayName: Check formatting
