trigger:
- master
- feature/*

jobs:
- job: rustfmt
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - template: azure-install-rust.yml

  - script: |
      rustup component add rustfmt
    displayName: Install rustfmt

  - script: |
      cd padre
      cargo fmt --all -- --check
    displayName: Check formatting

- job: unit_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - template: azure-install-rust.yml

  - script: |
      cd padre
      cargo test -- --nostdcapture
    displayName: Run Padre CLI testing

  - script: |
      whoami
      pwd
      uname -a
      add-apt-repository -y ppa:jonathonf/vim
      apt-get update
      apt-get install -y vim
    displayName: Install VIM
