trigger:
- master
- feature/*

jobs:
- job: rustfmt
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      rustup component add rustfmt
    displayName: Install rustfmt

  - script: |
      cd padre
      cargo fmt --all -- --check
    displayName: Check formatting

- job: padre_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      cd padre
      cargo test -- --nocapture
    env:
      RUST_BACKTRACE=1
    displayName: Run Padre CLI unit testing

  - script: |
      pip3 install behave
      cd padre/integrationn
      behave
    displayName: Run Padre CLI integration testing

- job: vim_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      whoami
      pwd
      uname -a
      add-apt-repository -y ppa:jonathonf/vim
      apt-get update
      apt-get install -y vim
    displayName: Install VIM

  - script: |
      cd padre
      cargo build
