trigger:
- master
- feature/*

jobs:
- job: rustfmt
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      rustup component add rustfmt
    displayName: Install rustfmt

  - script: |
      cd padre
      cargo fmt --all -- --check
    displayName: Check formatting

- job: padre_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      ls /dev
      sudo apt-get install software-properties-common python3 python3-pip python3-setuptools
      pip3 install wheel
      pip3 install behave pyhamcrest
    displayName: Install python dependencies

  - script: |
      cd padre
      cargo test -- --nocapture
    env:
      RUST_BACKTRACE: 1
# TODO: Turn this on when warnings fixed
#      RUSTFLAGS: '-D warnings'
    displayName: Run Padre CLI unit testing

  - script: |
      cd padre
      cargo build
# TODO: Turn this on when warnings fixed
#    env:
#      RUSTFLAGS: '-D warnings'
    displayName: Build Padre CLI

  - script: |
      cd padre/integration
      ~/.local/bin/behave
    displayName: Run Padre CLI integration testing

- job: vim_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/azure-install-rust.yml

  - script: |
      sudo add-apt-repository -y ppa:jonathonf/vim
      sudo apt-get update
      sudo apt-get install -y vim
      mkdir -p ~/.vim/autoload ~/.vim/bundle
      curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
      git clone https://github.com/junegunn/vader.vim ~/.vim/bundle/vader
      ln -s `pwd` ~/.vim/bundle/padre
    displayName: Install VIM and plugins

  - script: |
      sudo apt-get install -y lldb gcc
    displayName: Install lldb and build essentials

  - script: |
      cd padre
      cargo build
    displayName: Compile Padre CLI

  - script: |
      vim --version
      vim '+Vader! test/unit/*.vader'
    displayName: Run VIM unit tests

  - script: |
      vim '+Vader! test/integration/*.vader'
    displayName: Run VIM integration tests
