[package]
name = "padre"
version = "0.1.0"
authors = ["Steven Trotter <stevetrot@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
json = "0.11.13"
lazy_static = "1.3.0"
nix = "0.13.0"
regex = "1.1.2"
signal-hook = "0.1.8"
simulacrum = "0.3.0"
termios = "0.3.1"
