[package]
name = "padre"
version = "0.1.0"
authors = ["Steven Trotter <stevetrot@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
lazy_static = "1.3.0"
tokio = "0.1.22"
tokio-signal = "0.2"

[dev-dependencies]
mockall = "0.3.0"
